from server.forms.random_number_form import *
from server.forms.random_letter_form import *
from server.forms.random_item_form import *
from server.forms.coin_form import *
from server.forms.dice_form import *
from server.forms.card_form import *
from server.forms.link_sets_form import *
from server.forms.tournament_form import *
from server.forms.form_base import DrawFormError